### ISSUE TITLE
Mobile Number Login only || Skip the Screen which gives the option of Logging in with Twitter or Mobile

### ISSUE THREAD

**Issue by Abhi150688** [twitterdev/cannonball-android#10]
Hi, 
I am creating an adnroid app which supports login through mobile number only. How can I modify the Login page for this app so that I directly land on the page where the user is prompted for the mobile number. Basically I dont want to give the user an option for signing in, there is only Mobile NUmber sign-in that is supported.

**Comment by lfcipriani** [comment]
Hi,

Sorry, but right now we don't support this approach. You should always have the Digits button and this means that you're going to need to implement a login page.
