### ISSUE TITLE
Dead link in README.md

### ISSUE THREAD

**Issue by kaelaela** [twitterdev/cannonball-android#14]
Dead [this link](https://github.com/twitterdev/cannonball-android/blame/master/README.md#L59) .
「how to integrate the SDK」 (https://dev.twitter.com/archive/twitter-kit/android/integrate)

Instead, this link may be right.
https://docs.fabric.io/android/fabric/integration.html

**Comment by lfcipriani** [comment]
Hi @kaelaela, just fixed. Thanks for pointing out.
