### ISSUE TITLE
Question: How to add crash info upon crash?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [twitterdev/cannonball-android#15]
Since I don't see any example, tutorial or guides, about how to show Activity stack for each crash, I've decided to gather this information myself, by using this callback:
http://developer.android.com/reference/android/app/Application.html#registerActivityLifecycleCallbacks(android.app.Application.ActivityLifecycleCallbacks)

Thing is, I can't find where exactly can I send the entire stack of the activities upon app-crash.
There is no such listener.

Is it possible that what I just need to use is "Custom Keys" : 
https://docs.fabric.io/android/crashlytics/enhanced-reports.html#custom-keys
?
So that upon each event of activity, I set it to something different?
Or maybe use "Custom Logging" :
https://docs.fabric.io/android/crashlytics/enhanced-reports.html#custom-logging
so that for each event, i just log it ?

**Comment by andypiper** [comment]
You're probably best asking this question [on the developer forums](https://twittercommunity.com/c/fabric/crashlytics) instead of on this repo.

**Comment by AndroidDeveloperLB** [comment]
@andypiper The link you provided is of Twitter. I wanted to ask about the SDK of Crashlytics (AKA Fabric), which is supposed to be used in this sample.
As the sample is supposed to cover all of the features of the SDK, I wanted to ask how can I achieve the above.
Another scenario is that I'd like to report the used heap-memory when the crash occurred.

**Comment by andypiper** [comment]
Yes, I understand. Fabric is provided by Twitter, and the forums are where we are able to answer some of these questions.

**Comment by AndroidDeveloperLB** [comment]
I don't understand. Twitter is the owner of Crashlytics?
In any case, I've written this question on StackOverflow:
http://stackoverflow.com/q/37256595/878126
This is much more global and easy to find.

**Comment by andypiper** [comment]
As you wish - but yes, Crashlytics is part of Fabric which is part of Twitter, and twittercommunity.com is our developer community for the products. Thanks.
