### ISSUE TITLE
 Crashlytics.log();

### ISSUE THREAD

**Issue by chaozaiai** [twitterdev/cannonball-android#16]
if I use this method  Crashlytics.log("message");
then can I  see the log message on the  Crashlytics web?
I want use  Crashlytics.log() to  record the user's operation.
I test， but i can't find   these message on the   Crashlytics web.
thanks.

**Comment by lfcipriani** [comment]
The info you add to Crashlytics.log() is shown when you have a crash or non-fatal only. If you want to track user operation, you can use Answers Events (https://docs.fabric.io/android/answers/answers-events.html)

**Comment by chaozaiai** [comment]
@lfcipriani  thank you.  Sorry , I don't describe the problem which I try to solve clearly . Answers Events is helpful for  statistic and analysis about user's operation.  But I want have a log which  record the order of user's operation. Step1,Step2,Step3……     I want learn these infomation.  How can I do this?
Thanks.

**Comment by andypiper** [comment]
You may find it more useful to ask this question in the [Crashlytics developer forums](https://twittercommunity.com/c/fabric/crashlytics). However, as @lfcipriani said, you probably either want Answers Events, or to do your own logging, in order to achieve what you're asking for.
