### ISSUE TITLE
How to tweet an image on twitter

### ISSUE THREAD

**Issue by Abhinandan-Chada** [twitterdev/cannonball-android#9]
Can you please tell me the procedure for the image twwet throught Fabric sdk in android.

Thanks

**Comment by lfcipriani** [comment]
Hi, 

You can use TweetComposer for that. We have a sample at this source code:

                        final TweetComposer.Builder builder
                                = new TweetComposer.Builder(PoemHistoryActivity.this)
                                .text(getApplicationContext().getResources()
                                        .getString(R.string.share_poem_tweet_text) + " " + hashtag)
                                .image(imageUri);
                        builder.show();

Ref.: https://github.com/twitterdev/cannonball-android/blob/master/app/src/main/java/io/fabric/samples/cannonball/activity/PoemHistoryActivity.java#L291-L296

Remember that this image URI must to point to an image saved on the phone. We currently do not support images stored remotely.

Let me know if this works for you.

**Comment by Abhinandan-Chada** [comment]
thanks ....@ifcipriani
